version: '3'

services:
  node2:
    image: ethereum/client-go
    command: ["--datadir", "/gethdata", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcport", "8545", "--rpcapi", "eth,net,web3,personal,miner,clique", "--unlock", "322111479a4204b7bf4d52127c86ba8a0de0e80e", "--password", "/gethdata/password.txt", "--mine", "--allow-insecure-unlock"]
    ports:
      - "8542:8545"
    volumes:
      - ./node2:/gethdata
  node3:
    image: ethereum/client-go
    command: ["--datadir", "/gethdata", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcport", "8545", "--rpcapi", "eth,net,web3,personal,miner,clique", "--unlock", "", "--password", "/gethdata/password.txt", "--mine", "--allow-insecure-unlock"]
    ports:
      - "8543:8545"
    volumes:
      - ./node3:/gethdata
